// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package identitydb

import (
	"context"
	"database/sql"
)

type Querier interface {
	CountUsers(ctx context.Context, arg CountUsersParams) (int64, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (IdentityUsers, error)
	DeletePasswordCredential(ctx context.Context, userID string) error
	DeleteSession(ctx context.Context, id string) error
	DeleteSessionsForUser(ctx context.Context, userID string) error
	DeleteUser(ctx context.Context, id string) error
	GetPasswordCredential(ctx context.Context, userID string) (IdentityPasswords, error)
	GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (IdentitySessions, error)
	GetUser(ctx context.Context, id string) (IdentityUsers, error)
	GetUserByHandle(ctx context.Context, handle string) (IdentityUsers, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]IdentityUsers, error)
	MarkUserLogin(ctx context.Context, arg MarkUserLoginParams) error
	RevokeSession(ctx context.Context, arg RevokeSessionParams) error
	RevokeSessionsForUser(ctx context.Context, arg RevokeSessionsForUserParams) error
	TouchSession(ctx context.Context, arg TouchSessionParams) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error
	UpdateUserState(ctx context.Context, arg UpdateUserStateParams) (sql.Result, error)
	UpsertPasswordCredential(ctx context.Context, arg UpsertPasswordCredentialParams) error
}

var _ Querier = (*Queries)(nil)
