// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package identitydb

import (
	"database/sql"
	"time"
)

type IdentityPasswords struct {
	UserID            string    `json:"user_id"`
	Scheme            string    `json:"scheme"`
	Hash              string    `json:"hash"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}

type IdentitySessions struct {
	ID            string       `json:"id"`
	TokenHash     []byte       `json:"token_hash"`
	UserID        string       `json:"user_id"`
	LoginIp       string       `json:"login_ip"`
	LastIp        string       `json:"last_ip"`
	BindingHash   []byte       `json:"binding_hash"`
	UserAgentHash []byte       `json:"user_agent_hash"`
	ExpiresAt     time.Time    `json:"expires_at"`
	CreatedAt     time.Time    `json:"created_at"`
	LastSeenAt    time.Time    `json:"last_seen_at"`
	RevokedAt     sql.NullTime `json:"revoked_at"`
	RevokedReason string       `json:"revoked_reason"`
}

type IdentityUsers struct {
	ID          string       `json:"id"`
	Handle      string       `json:"handle"`
	DisplayName string       `json:"display_name"`
	Email       string       `json:"email"`
	AvatarUrl   string       `json:"avatar_url"`
	State       string       `json:"state"`
	DisabledAt  sql.NullTime `json:"disabled_at"`
	LastLoginAt sql.NullTime `json:"last_login_at"`
	CreatedAt   time.Time    `json:"created_at"`
	UpdatedAt   time.Time    `json:"updated_at"`
}
