// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package identitydb

import (
	"context"
	"database/sql"
	"time"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM identity_users
WHERE (CAST($1 AS VARCHAR) = '' OR handle LIKE '%' || CAST($1 AS VARCHAR) || '%' OR display_name LIKE '%' || CAST($1 AS VARCHAR) || '%' OR email LIKE '%' || CAST($1 AS VARCHAR) || '%')
  AND (CAST($2 AS VARCHAR) = '' OR state = CAST($2 AS VARCHAR))
`

type CountUsersParams struct {
	Keyword string `json:"keyword"`
	State   string `json:"state"`
}

func (q *Queries) CountUsers(ctx context.Context, arg CountUsersParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers, arg.Keyword, arg.State)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO identity_sessions (
    id, token_hash, user_id, login_ip, last_ip, binding_hash, user_agent_hash,
    expires_at, created_at, last_seen_at, revoked_at, revoked_reason
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type CreateSessionParams struct {
	ID            string       `json:"id"`
	TokenHash     []byte       `json:"token_hash"`
	UserID        string       `json:"user_id"`
	LoginIp       string       `json:"login_ip"`
	LastIp        string       `json:"last_ip"`
	BindingHash   []byte       `json:"binding_hash"`
	UserAgentHash []byte       `json:"user_agent_hash"`
	ExpiresAt     time.Time    `json:"expires_at"`
	CreatedAt     time.Time    `json:"created_at"`
	LastSeenAt    time.Time    `json:"last_seen_at"`
	RevokedAt     sql.NullTime `json:"revoked_at"`
	RevokedReason string       `json:"revoked_reason"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.TokenHash,
		arg.UserID,
		arg.LoginIp,
		arg.LastIp,
		arg.BindingHash,
		arg.UserAgentHash,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.LastSeenAt,
		arg.RevokedAt,
		arg.RevokedReason,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO identity_users (
    id, handle, display_name, email, avatar_url, state, disabled_at, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, handle, display_name, email, avatar_url, state, disabled_at, last_login_at, created_at, updated_at
`

type CreateUserParams struct {
	ID          string       `json:"id"`
	Handle      string       `json:"handle"`
	DisplayName string       `json:"display_name"`
	Email       string       `json:"email"`
	AvatarUrl   string       `json:"avatar_url"`
	State       string       `json:"state"`
	DisabledAt  sql.NullTime `json:"disabled_at"`
	CreatedAt   time.Time    `json:"created_at"`
	UpdatedAt   time.Time    `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (IdentityUsers, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Handle,
		arg.DisplayName,
		arg.Email,
		arg.AvatarUrl,
		arg.State,
		arg.DisabledAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i IdentityUsers
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.DisplayName,
		&i.Email,
		&i.AvatarUrl,
		&i.State,
		&i.DisabledAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePasswordCredential = `-- name: DeletePasswordCredential :exec
DELETE FROM identity_passwords WHERE user_id = $1
`

func (q *Queries) DeletePasswordCredential(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deletePasswordCredential, userID)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM identity_sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const deleteSessionsForUser = `-- name: DeleteSessionsForUser :exec
DELETE FROM identity_sessions WHERE user_id = $1
`

func (q *Queries) DeleteSessionsForUser(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionsForUser, userID)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM identity_users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getPasswordCredential = `-- name: GetPasswordCredential :one
SELECT user_id, scheme, hash, password_changed_at, created_at, updated_at FROM identity_passwords WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetPasswordCredential(ctx context.Context, userID string) (IdentityPasswords, error) {
	row := q.db.QueryRowContext(ctx, getPasswordCredential, userID)
	var i IdentityPasswords
	err := row.Scan(
		&i.UserID,
		&i.Scheme,
		&i.Hash,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, token_hash, user_id, login_ip, last_ip, binding_hash, user_agent_hash, expires_at, created_at, last_seen_at, revoked_at, revoked_reason FROM identity_sessions WHERE token_hash = $1 LIMIT 1
`

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (IdentitySessions, error) {
	row := q.db.QueryRowContext(ctx, getSessionByTokenHash, tokenHash)
	var i IdentitySessions
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.UserID,
		&i.LoginIp,
		&i.LastIp,
		&i.BindingHash,
		&i.UserAgentHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.RevokedReason,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, handle, display_name, email, avatar_url, state, disabled_at, last_login_at, created_at, updated_at FROM identity_users WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id string) (IdentityUsers, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i IdentityUsers
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.DisplayName,
		&i.Email,
		&i.AvatarUrl,
		&i.State,
		&i.DisabledAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByHandle = `-- name: GetUserByHandle :one
SELECT id, handle, display_name, email, avatar_url, state, disabled_at, last_login_at, created_at, updated_at FROM identity_users WHERE handle = $1 LIMIT 1
`

func (q *Queries) GetUserByHandle(ctx context.Context, handle string) (IdentityUsers, error) {
	row := q.db.QueryRowContext(ctx, getUserByHandle, handle)
	var i IdentityUsers
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.DisplayName,
		&i.Email,
		&i.AvatarUrl,
		&i.State,
		&i.DisabledAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, handle, display_name, email, avatar_url, state, disabled_at, last_login_at, created_at, updated_at FROM identity_users
WHERE (CAST($1 AS VARCHAR) = '' OR handle LIKE '%' || CAST($1 AS VARCHAR) || '%' OR display_name LIKE '%' || CAST($1 AS VARCHAR) || '%' OR email LIKE '%' || CAST($1 AS VARCHAR) || '%')
  AND (CAST($2 AS VARCHAR) = '' OR state = CAST($2 AS VARCHAR))
ORDER BY created_at DESC LIMIT $4 OFFSET $3
`

type ListUsersParams struct {
	Keyword    string `json:"keyword"`
	State      string `json:"state"`
	PageOffset int32  `json:"page_offset"`
	PageSize   int32  `json:"page_size"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]IdentityUsers, error) {
	rows, err := q.db.QueryContext(ctx, listUsers,
		arg.Keyword,
		arg.State,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdentityUsers{}
	for rows.Next() {
		var i IdentityUsers
		if err := rows.Scan(
			&i.ID,
			&i.Handle,
			&i.DisplayName,
			&i.Email,
			&i.AvatarUrl,
			&i.State,
			&i.DisabledAt,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markUserLogin = `-- name: MarkUserLogin :exec
UPDATE identity_users SET last_login_at = $1, updated_at = $2 WHERE id = $3
`

type MarkUserLoginParams struct {
	LastLoginAt sql.NullTime `json:"last_login_at"`
	UpdatedAt   time.Time    `json:"updated_at"`
	ID          string       `json:"id"`
}

func (q *Queries) MarkUserLogin(ctx context.Context, arg MarkUserLoginParams) error {
	_, err := q.db.ExecContext(ctx, markUserLogin, arg.LastLoginAt, arg.UpdatedAt, arg.ID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE identity_sessions SET revoked_at = $1, revoked_reason = $2, last_ip = $3, last_seen_at = $4 WHERE id = $5
`

type RevokeSessionParams struct {
	RevokedAt     sql.NullTime `json:"revoked_at"`
	RevokedReason string       `json:"revoked_reason"`
	LastIp        string       `json:"last_ip"`
	LastSeenAt    time.Time    `json:"last_seen_at"`
	ID            string       `json:"id"`
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) error {
	_, err := q.db.ExecContext(ctx, revokeSession,
		arg.RevokedAt,
		arg.RevokedReason,
		arg.LastIp,
		arg.LastSeenAt,
		arg.ID,
	)
	return err
}

const revokeSessionsForUser = `-- name: RevokeSessionsForUser :exec
UPDATE identity_sessions SET revoked_at = $1, revoked_reason = $2 WHERE user_id = $3 AND revoked_at IS NULL
`

type RevokeSessionsForUserParams struct {
	RevokedAt     sql.NullTime `json:"revoked_at"`
	RevokedReason string       `json:"revoked_reason"`
	UserID        string       `json:"user_id"`
}

func (q *Queries) RevokeSessionsForUser(ctx context.Context, arg RevokeSessionsForUserParams) error {
	_, err := q.db.ExecContext(ctx, revokeSessionsForUser, arg.RevokedAt, arg.RevokedReason, arg.UserID)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE identity_sessions SET last_ip = $1, last_seen_at = $2 WHERE id = $3
`

type TouchSessionParams struct {
	LastIp     string    `json:"last_ip"`
	LastSeenAt time.Time `json:"last_seen_at"`
	ID         string    `json:"id"`
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.ExecContext(ctx, touchSession, arg.LastIp, arg.LastSeenAt, arg.ID)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :exec
UPDATE identity_users SET display_name = $1, email = $2, avatar_url = $3, updated_at = $4 WHERE id = $5
`

type UpdateUserProfileParams struct {
	DisplayName string    `json:"display_name"`
	Email       string    `json:"email"`
	AvatarUrl   string    `json:"avatar_url"`
	UpdatedAt   time.Time `json:"updated_at"`
	ID          string    `json:"id"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error {
	_, err := q.db.ExecContext(ctx, updateUserProfile,
		arg.DisplayName,
		arg.Email,
		arg.AvatarUrl,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateUserState = `-- name: UpdateUserState :execresult
UPDATE identity_users SET state = $1, disabled_at = $2, updated_at = $3 WHERE id = $4
`

type UpdateUserStateParams struct {
	State      string       `json:"state"`
	DisabledAt sql.NullTime `json:"disabled_at"`
	UpdatedAt  time.Time    `json:"updated_at"`
	ID         string       `json:"id"`
}

func (q *Queries) UpdateUserState(ctx context.Context, arg UpdateUserStateParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateUserState,
		arg.State,
		arg.DisabledAt,
		arg.UpdatedAt,
		arg.ID,
	)
}

const upsertPasswordCredential = `-- name: UpsertPasswordCredential :exec
INSERT INTO identity_passwords (user_id, scheme, hash, password_changed_at, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT(user_id) DO UPDATE SET
    scheme = excluded.scheme,
    hash = excluded.hash,
    password_changed_at = excluded.password_changed_at,
    updated_at = excluded.updated_at
`

type UpsertPasswordCredentialParams struct {
	UserID            string    `json:"user_id"`
	Scheme            string    `json:"scheme"`
	Hash              string    `json:"hash"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}

func (q *Queries) UpsertPasswordCredential(ctx context.Context, arg UpsertPasswordCredentialParams) error {
	_, err := q.db.ExecContext(ctx, upsertPasswordCredential,
		arg.UserID,
		arg.Scheme,
		arg.Hash,
		arg.PasswordChangedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
